name: Daily Commit

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 4PM UTC (Noon Eastern)
  workflow_dispatch:       # Lets you manually run it from the Actions tab

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git config user.name "HdCrxti"
          git config user.email "jacobdaviddutra@gmail.com"
          git commit --allow-empty -m "Daily commit"
          git push
