name: Daily Commit

on:
  schedule:
    - cron: "0 16 * * *"   # 12 PM ET
    - cron: "0 18 * * *"   # 2 PM ET
    - cron: "0 20 * * *"   # 4 PM ET
    - cron: "0 22 * * *"   # 6 PM ET
    - cron: "0 0 * * *"    # 8 PM ET
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make empty commit and push
        run: |
          git config user.name "HdCxrti"
          git config user.email "hdcxrti@gmail.com"
          git commit --allow-empty -m "Daily commit"
          git push https://x-access-token:${{ secrets.PAT_DAILY_COMMIT }}@github.com/${{ github.repository }} HEAD:main
