name: Daily Commit

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make empty commit and push
        run: |
          git config user.name "HdCrxti"
          git config user.email "jacobdaviddutra@gmail.com"
          git commit --allow-empty -m "Daily commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
